function m(b,a,c,d,e){b.h.rb(b.ub,a,c,d,e)}function n(b,a,c,d){b.h.ba?m(b,a,c,d):b.h.af()._OnMessageFromDOM({type:"event",component:b.ub,handler:a,dispatchOpts:d||null,data:c,responseId:null})}function p(b,a,c){b.h.B(b.ub,a,c)}function v(b,a){for(const [c,d]of a)p(b,c,d)}function w(b){b.Yb||(b.h.Hc(b.re),b.Yb=!0)}function aa(b){b.Yb&&(b.h.Pd(b.re),b.Yb=!1)}window.kb=class{constructor(b,a){this.h=b;this.ub=a;this.Yb=!1;this.re=()=>this.Ia()}tc(){}Ia(){}};
window.Nf=class{constructor(){this.td=-1}l(){-1!==this.td&&(self.clearTimeout(this.td),this.td=-1)}};"use strict";class ba{constructor(b){this.Wa=b;this.Zc=!1;this.gd=!0;this.yb=this.sa=this.ud=-1}}
function ca(b,a){const c=a.elementId,d=b.Bd(c,a),e=new ba(d);b.za.set(c,e);d.style.boxSizing="border-box";d.style.display="none";e.gd=!!a.isVisible;d.addEventListener("focus",()=>{x(b,"elem-focused",c)});d.addEventListener("blur",()=>{x(b,"elem-blurred",c)});const f=a.htmlIndex;e.ud=f;e.yb=a.htmlZIndex;b.Ma&&(a=b.h.xc(f),e.sa=a,b.h.lb(a).appendChild(d))}function y(b,a,c){p(b,a,d=>{const e=z(b,d.elementId);return c(e,d)})}
function z(b,a){b=b.za.get(a);if(!b)throw Error(`no element with id ${a}`);return b.Wa}function x(b,a,c,d){d||(d={});d.elementId=c;m(b,a,d)}
window.wc=class extends self.kb{constructor(b){super(b,"video");this.za=new Map;this.Ma=!0;v(this,[["create",a=>ca(this,a)],["destroy",a=>{a=a.elementId;const c=z(this,a);this.Dd(c);this.Ma&&c.parentElement.removeChild(c);this.za.delete(a)}],["set-visible",a=>{if(this.Ma){var c=this.za.get(a.elementId),d=c.Wa;c.Zc?d.style.display=a.isVisible?"":"none":c.gd=!!a.isVisible}}],["update-position",a=>{if(this.Ma){var c=this.za.get(a.elementId),d=c.Wa,e=this.h;d.style.left=a.left+"px";d.style.top=a.top+
"px";d.style.width=a.width+"px";d.style.height=a.height+"px";var f=a.fontSize;null!==f&&(d.style.fontSize=f+"em");f=a.htmlIndex;c.ud=f;f=e.xc(f);f!==c.sa&&(d.remove(),e.lb(f).appendChild(d),c.sa=f,e.Sc());a=a.htmlZIndex;a!==c.yb&&(c.yb=a,e.Sc());c.Zc||(c.Zc=!0,c.gd&&(d.style.display=""))}}],["update-state",a=>{z(this,a.elementId);this.Id()}],["focus",a=>this.Pc(a)],["set-css-style",a=>{const c=z(this,a.elementId),d=a.prop;a=a.val;d.startsWith("--")?c.style.setProperty(d,a):c.style[d]=a}],["set-attribute",
a=>{z(this,a.elementId).setAttribute(a.name,a.val)}],["remove-attribute",a=>{z(this,a.elementId).removeAttribute(a.name)}]]);y(this,"get-element",a=>a)}Bd(){throw Error("required override");}Dd(){}Id(){throw Error("required override");}Pc(b){var a=z(this,b.elementId);b.focus?a.focus():a.blur()}};"use strict";const ea=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),A=/android/i.test(navigator.userAgent),fa=/safari/i.test(navigator.userAgent)&&!/(chrome|chromium|edg\/|OPR\/|nwjs)/i.test(navigator.userAgent);
let ha=0;function B(b){const a=document.createElement("script");a.async=!1;a.type="module";return b.Df?new Promise(c=>{const d="c3_resolve_"+ha;++ha;self[d]=c;a.textContent=b.Hf+`\n\nself["${d}"]();`;document.head.appendChild(a)}):new Promise((c,d)=>{a.onload=c;a.onerror=d;a.src=b;document.head.appendChild(a)})}
async function ia(){if(!navigator.userActivation||"undefined"===typeof OffscreenCanvas)return!1;try{let b=!1;const a=new Worker(URL.createObjectURL(new Blob(['\n\tself.addEventListener("message", () =>\n\t{\n\t\ttry {\n\t\t\tconst offscreenCanvas = new OffscreenCanvas(32, 32);\n\t\t\tconst gl = offscreenCanvas.getContext("webgl");\n\t\t\tself.postMessage(!!gl);\n\t\t}\n\t\tcatch (err)\n\t\t{\n\t\t\tconsole.warn("Feature detection worker error:", err);\n\t\t\tself.postMessage(false);\n\t\t}\n\t});'],{type:"text/javascript"})),
{get type(){b=!0}}),c=await new Promise(d=>{a.addEventListener("message",e=>{a.terminate();d(e.data)});a.postMessage("")});return b&&c}catch(b){return console.warn("Error feature detecting worker mode: ",b),!1}}let C=new Audio;
const ja={"audio/webm; codecs=opus":!!C.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!C.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!C.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!C.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!C.canPlayType("audio/mp4"),"audio/mpeg":!!C.canPlayType("audio/mpeg")};C=null;async function ka(b){b=await la(b);return(new TextDecoder("utf-8")).decode(b)}
function la(b){return new Promise((a,c)=>{const d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsArrayBuffer(b)})}const ma=[];let E=0;window.RealFile=window.File;const F=[],na=new Map,oa=new Map;let pa=0;const ta=[];self.runOnStartup=function(b){if("function"!==typeof b)throw Error("runOnStartup called without a function");ta.push(b)};const ua=new Set(["cordova","playable-ad","instant-games"]);let va=!1;
window.ya=class b{constructor(a){this.ba=a.Jf;this.Ca=null;this.aa="";this.eb=a.Gf;this.Mb={};this.Ya=this.xa=null;this.Va=[];this.oa=null;this.ee=!0;this.M=[];this.nd=[];this.od=!1;this.se=()=>this.Ze();this.cd=!1;this.Zd=0;this.Ab=null;this.cb=-1;this.yf=()=>this.kf();this.Jb=new Set;this.vd=null;this.te=[];this.u=a.ue;this.Zb="file"===location.protocol.substr(0,4);if("playable-ad"===this.u||"instant-games"===this.u)this.ba=!1;fa&&(this.ba=!1);if("cordova"===this.u&&this.ba&&A){const c=/Chrome\/(\d+)/i.exec(navigator.userAgent);
c&&90<=parseInt(c[1],10)||(this.ba=!1)}this.qa()?self.chrome.webview.addEventListener("message",c=>this.Od(c.data)):"macos-wkwebview"===this.u&&(self.C3WrapperOnMessage=c=>this.Od(c));this.bc=this.ua=null;"html5"!==this.u||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.B("canvas","update-size",c=>this.pf(c));this.B("canvas","set-html-layer-count",
c=>this._OnSetHTMLLayerCount(c));this.B("canvas","cleanup-html-layers",()=>this.ef());this.B("runtime","cordova-fetch-local-file",c=>this.ff(c));this.B("runtime","create-job-worker",()=>this.gf());this.B("runtime","send-wrapper-extension-message",c=>this.nf(c));"cordova"===this.u?document.addEventListener("deviceready",()=>this.Md(a)):this.Md(a)}l(){this.Ic();this.Ca&&(this.Ca=this.Ca.onmessage=null);this.xa&&(this.xa.terminate(),this.xa=null);this.Ya&&(this.Ya.l(),this.Ya=null);for(const {canvas:a,
hb:c}of this.M)a.remove(),c.remove();this.M.length=0}Ed(){return this.M[0].canvas}xc(a){return Math.min(a,this.M.length-1)}lb(a){if(0>a||a>=this.M.length)throw new RangeError("invalid canvas layer");return this.M[a].hb}_GetHTMLWrapElement(a){return this.lb(a)}Pe(){return ea&&"cordova"===this.u}pb(){const a=navigator.userAgent;return ea&&ua.has(this.u)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}Ne(){return A}Dc(){return A&&ua.has(this.u)}Gd(){return"windows-webview2"===this.u||!!("preview"===
this.u&&window.chrome&&window.chrome.webview&&window.chrome.webview.postMessage)}qa(){return this.Gd()||"xbox-uwp-webview2"===this.u}async Md(a){this.ba&&!await ia()&&(this.ba=!1);"macos-wkwebview"===this.u?this.Ja({type:"ready"}):this.qa()&&(this.rf(),this.te=(await this.df()).registeredComponentIds);if("playable-ad"===this.u){this.ua=self.c3_base64files;this.bc={};await this.We();for(let d=0,e=a.gb.length;d<e;++d){var c=a.gb[d];this.bc.hasOwnProperty(c)?a.gb[d]={Df:!0,Hf:this.bc[c]}:this.ua.hasOwnProperty(c)&&
(a.gb[d]=URL.createObjectURL(this.ua[c]))}a.sc=[]}if("nwjs"===this.u&&self.nw&&self.nw.App.manifest["c3-steam-mode"]){let d=0;this.Hc(()=>{d++;document.documentElement.style.opacity=0===d%2?"1":"0.999"})}a.Ff?this.aa=a.Ff:(c=location.origin,this.aa=("null"===c?"file:///":c)+location.pathname,c=this.aa.lastIndexOf("/"),-1!==c&&(this.aa=this.aa.substr(0,c+1)));a.Lf&&(this.Mb=a.Lf);c=new MessageChannel;this.Ca=c.port1;this.Ca.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&
window.c3_addPortMessageHandler(d=>this.jf(d));this.Ab=new self.Qe(this);await wa(this.Ab);"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((d,e)=>{window.AndroidFullScreen.immersiveMode(d,e)})}catch(d){console.error("Failed to enter Android immersive mode: ",d)}this.ba?await this.cf(a,c.port2):await this.bf(a,c.port2)}Kc(a){a=this.Mb.hasOwnProperty(a)?this.Mb[a]:a.endsWith("/workermain.js")&&this.Mb.hasOwnProperty("workermain.js")?
this.Mb["workermain.js"]:"playable-ad"===this.u&&this.ua.hasOwnProperty(a)?this.ua[a]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async vc(a,c,d){if(a.startsWith("blob:"))return new Worker(a,d);if("cordova"===this.u&&this.Zb)return a=await this.Nb(d.Cf?a:this.eb+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),d);a=new URL(a,c);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),
d)}return new Worker(a,d)}ra(){return Math.max(window.innerWidth,1)}ia(){return Math.max(window.innerHeight,1)}zc(){return this.qa()||(new Set(["cordova","nwjs","macos-wkwebview"])).has(this.u)?"standalone":window.matchMedia("(display-mode: fullscreen)").matches?"fullscreen":window.matchMedia("(display-mode: standalone)").matches?"standalone":window.matchMedia("(display-mode: minimal-ui)").matches?"minimal-ui":navigator.standalone?"standalone":"browser"}Ld(a){var c=this.aa,d=location.href,e=this.ra(),
f=this.ia(),g=this.zc(),h=window.devicePixelRatio,k=b.ob(),l=a.Rf,q=window.cr_previewImageBlobs||this.ua,r=window.cr_previewProjectFileBlobs,t=window.cr_previewProjectFiles,u=window.cr_swClientId||"";a=a.ue;var da=(new URLSearchParams(self.location.search)).has("debug"),G=this.Ab;return{runtimeBaseUrl:c,previewUrl:d,windowInnerWidth:e,windowInnerHeight:f,cssDisplayMode:g,devicePixelRatio:h,isFullscreen:k,projectData:l,previewImageBlobs:q,previewProjectFileBlobs:r,previewProjectFileSWUrls:t,swClientId:u,
exportType:a,isDebug:da,ife:!!self.Qf,jobScheduler:{inputPort:G.bd,outputPort:G.md,maxNumWorkers:G.vf},supportedAudioFormats:ja,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.eb+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.eb+"opus.wasm.wasm",isFileProtocol:this.Zb,isiOSCordova:this.Pe(),isiOSWebView:this.pb(),isWindowsWebView2:this.Gd(),isAnyWebView2Wrapper:this.qa(),wrapperComponentIds:this.te,isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async cf(a,c){const d=
this.Kc(a.Kf);"preview"===this.u?(this.xa=new Worker("previewworker.js",{type:"module",name:"Runtime"}),await new Promise((l,q)=>{const r=t=>{this.xa.removeEventListener("message",r);t.data&&"ok"===t.data.type?l():q()};this.xa.addEventListener("message",r);this.xa.postMessage({type:"construct-worker-init","import":(new URL(d,this.aa)).toString()})})):this.xa=await this.vc(d,this.aa,{type:"module",name:"Runtime",Cf:!0});const e=document.createElement("canvas");e.style.display="none";const f=e.transferControlToOffscreen();
document.body.appendChild(e);const g=document.createElement("div");g.className="c3htmlwrap";document.body.appendChild(g);this.M.push({canvas:e,hb:g});window.c3canvas=e;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let h=a.sc||[],k=a.gb;h=await Promise.all(h.map(l=>this.Sa(l)));k=await Promise.all(k.map(l=>this.Sa(l)));if("cordova"===this.u)for(let l=0,q=a.rc.length;l<q;++l){const r=a.rc[l],t=r[0];if(t===a.wd||"scriptsInEvents.js"===t||t.endsWith("/scriptsInEvents.js"))r[1]=await this.Sa(t)}this.xa.postMessage(Object.assign(this.Ld(a),
{type:"init-runtime",isInWorker:!0,messagePort:c,canvas:f,workerDependencyScripts:h,engineScripts:k,projectScripts:a.rc,mainProjectScript:a.wd,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[c,f,...xa(this.Ab)]);this.Va=F.map(l=>new l(this));this.Kd();za(e);Aa(g);Ba(this.oa);self.c3_callFunction=(l,q)=>{var r=this.oa;return r.h.Hd(r.ub,"js-invoke-function",{name:l,params:q})};"preview"===this.u&&(self.goToLastErrorScript=()=>this.rb("runtime","go-to-last-error-script"))}async bf(a,c){const d=
document.createElement("canvas");d.style.display="none";document.body.appendChild(d);var e=document.createElement("div");e.className="c3htmlwrap";document.body.appendChild(e);this.M.push({canvas:d,hb:e});window.c3canvas=d;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();this.Va=F.map(h=>new h(this));this.Kd();za(d);Aa(e);e=a.gb.map(h=>"string"===typeof h?(new URL(h,this.aa)).toString():h);if(Array.isArray(a.sc)){var f=[...a.sc].map(h=>h instanceof Blob?URL.createObjectURL(h):h);e.unshift(...f)}e=
await Promise.all(e.map(h=>this.Sa(h)));await Promise.all(e.map(h=>B(h)));e=self.C3_ProjectScriptsStatus;f=a.wd;const g=a.rc;for(let [h,k]of g)if(k||(k=h),h===f)try{k=await this.Sa(k),await B(k),"preview"!==this.u||e[h]||this.Qd(h,"main script did not run to completion")}catch(l){this.Qd(h,l)}else if("scriptsInEvents.js"===h||h.endsWith("/scriptsInEvents.js"))k=await this.Sa(k),await B(k);"preview"===this.u&&"object"!==typeof self.Mf.Of?(this.Sb(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),
alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.Ld(a),{isInWorker:!1,messagePort:c,canvas:d,runOnStartupFunctions:ta}),Ba(this.oa),this.Nd(),this.Ya=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.Ya,a))}Qd(a,c){this.Sb();console.error(`[Preview] Failed to load project main script (${a}): `,c);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}Nd(){this.Sb()}Sb(){const a=
window.cr_previewLoadingElem;a&&(a.parentElement.removeChild(a),window.cr_previewLoadingElem=null)}async gf(){const a=await Ca(this.Ab);return{outputPort:a,transferables:[a]}}pf(a){if(!this.cd){var c=a.styleWidth+"px",d=a.styleHeight+"px",e=a.marginLeft+"px",f=a.marginTop+"px";for(const {canvas:g,hb:h}of this.M)g.style.width=c,g.style.height=d,g.style.marginLeft=e,g.style.marginTop=f,h.style.width=c,h.style.height=d,h.style.marginLeft=e,h.style.marginTop=f,this.ee&&(g.style.display="",h.style.display=
"");document.documentElement.style.setProperty("--construct-scale",a.displayScale);this.ee=!1}}_OnSetHTMLLayerCount(a){var c=a.count,d=a.immediate,e=a.styleWidth+"px",f=a.styleHeight+"px";const g=a.marginLeft+"px",h=a.marginTop+"px";a=[];const k=[];if(c<this.M.length)for(;this.M.length>c;){const {canvas:l,hb:q}=this.M.pop();q.remove();this.ba&&!d?this.nd.push(l):l.remove()}else if(c>this.M.length)for(let l=0,q=c-this.M.length;l<q;++l)c=document.createElement("canvas"),c.classList.add("c3overlay"),
this.ba?(d=c.transferControlToOffscreen(),a.push(d),k.push(d)):a.push(c),document.body.appendChild(c),d=document.createElement("div"),d.classList.add("c3htmlwrap","c3overlay"),document.body.appendChild(d),c.style.width=e,c.style.height=f,c.style.marginLeft=g,c.style.marginTop=h,d.style.width=e,d.style.height=f,d.style.marginLeft=g,d.style.marginTop=h,za(c),Aa(d),this.M.push({canvas:c,hb:d});for(const l of this.Va)if(l instanceof window.wc&&l.Ma)for(const q of l.za.values())e=l.h.xc(q.ud),f=q.sa,-1!==
e&&-1!==f&&e!==f&&(f=q.Wa,f.remove(),l.h.lb(e).appendChild(f),q.sa=e);this.Sc();return{addedCanvases:a,transferables:k}}ef(){for(const a of this.nd)a.remove();this.nd.length=0}Sc(){this.od||(this.od=!0,this.Hc(this.se))}Ze(){this.Pd(this.se);this.od=!1;let a=[];for(var c of this.Va)if(c instanceof window.wc){var d=c.Ma?[...c.za.values()]:null;d&&a.push(...d)}a.sort((g,h)=>{const k=g.sa,l=h.sa;return k!==l?k-l:g.yb-h.yb});let e=d=c=0,f=a.length;for(;e<f;++e){const g=a[e];g.sa!==c&&(this.Jd(c,a.slice(d,
e)),c=g.sa,d=e)}d<e&&this.Jd(c,a.slice(d,e))}Jd(a,c){if(!(1>=c.length||a>=this.M.length)){c=c.map(k=>k.Wa);var d=new Set(c);a=this.lb(a);for(var e=Array.from(a.children).filter(k=>d.has(k)),f=0,g=Math.min(c.length,e.length);f<g&&c[f]===e[f];++f);for(var h=f;h<g;++h)e[h].remove();for(h=f;h<g;++h)a.appendChild(c[h])}}af(){if(this.ba)throw Error("not available in worker mode");return this.Ya}rb(a,c,d,e,f){this.Ca.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:null},
f)}Hd(a,c,d,e,f){const g=pa++,h=new Promise((k,l)=>{oa.set(g,{resolve:k,reject:l})});this.Ca.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:g},f);return h}_OnMessageFromRuntime(a){const c=a.type;if("event"===c)return this.hf(a);if("result"===c)this.lf(a);else if("runtime-ready"===c)this.mf();else if("alert-error"===c)this.Sb(),alert(a.message);else if("creating-runtime"===c)this.Nd();else throw Error(`unknown message '${c}'`);}hf(a){const c=a.component,d=a.handler,
e=a.data,f=a.responseId;if(a=na.get(c))if(a=a.get(d)){var g=null;try{g=a(e)}catch(h){console.error(`Exception in '${c}' handler '${d}':`,h);null!==f&&this.Rb(f,!1,""+h);return}if(null===f)return g;g&&g.then?g.then(h=>this.Rb(f,!0,h)).catch(h=>{console.error(`Rejection from '${c}' handler '${d}':`,h);this.Rb(f,!1,""+h)}):this.Rb(f,!0,g)}else console.warn(`[DOM] No handler '${d}' for component '${c}'`);else console.warn(`[DOM] No event handlers for component '${c}'`)}Rb(a,c,d){let e;d&&d.transferables&&
(e=d.transferables);this.Ca.postMessage({type:"result",responseId:a,isOk:c,result:d},e)}lf(a){const c=a.responseId,d=a.isOk;a=a.result;const e=oa.get(c);d?e.resolve(a):e.reject(a);oa.delete(c)}B(a,c,d){let e=na.get(a);e||(e=new Map,na.set(a,e));if(e.has(c))throw Error(`[DOM] Component '${a}' already has handler '${c}'`);e.set(c,d)}static ib(a){if(F.includes(a))throw Error("DOM handler already added");F.push(a)}Kd(){for(const a of this.Va)if("runtime"===a.ub){this.oa=a;return}throw Error("cannot find runtime DOM handler");
}jf(a){this.rb("debugger","message",a)}mf(){for(const a of this.Va)a.tc()}static ob(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||va)}static Tb(a){va=!!a}Hc(a){this.Jb.add(a);this.Rc()}Pd(a){this.Jb.delete(a);0===this.Jb.size&&this.Ic()}Rc(){-1===this.cb&&0<this.Jb.size&&(this.cb=requestAnimationFrame(this.yf))}Ic(){-1!==this.cb&&(cancelAnimationFrame(this.cb),this.cb=-1)}kf(){this.cb=-1;for(const a of this.Jb)a();this.Rc()}ca(a){this.oa.ca(a)}ha(a){this.oa.ha(a)}Qc(){this.oa.Qc()}Qb(a){this.oa.Qb(a)}Oe(){return!!ja["audio/webm; codecs=opus"]}async sf(a){a=
await this.Hd("runtime","opus-decode",{arrayBuffer:a},null,[a]);return new Float32Array(a)}Se(a){this.cd=!0;this.Zd=a}Me(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}Fd(a){return!this.Me(a)}async Sa(a){return"cordova"===this.u&&(a.startsWith("file:")||this.Zb&&this.Fd(a))?(a.startsWith(this.aa)&&(a=a.substr(this.aa.length)),a=await this.Nb(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async ff(a){const c=a.filename;switch(a.as){case "text":return await this.Le(c);
case "buffer":return await this.Nb(c);default:throw Error("unsupported type");}}Ad(a){const c=window.cordova.file.applicationDirectory+"www/"+a;return new Promise((d,e)=>{window.resolveLocalFileSystemURL(c,f=>{f.file(d,e)},e)})}async Le(a){a=await this.Ad(a);return await ka(a)}Jc(){if(ma.length&&!(8<=E)){E++;var a=ma.shift();this.Xe(a.filename,a.If,a.Bf)}}Nb(a){return new Promise((c,d)=>{ma.push({filename:a,If:e=>{E--;this.Jc();c(e)},Bf:e=>{E--;this.Jc();d(e)}});this.Jc()})}async Xe(a,c,d){try{const e=
await this.Ad(a),f=await la(e);c(f)}catch(e){d(e)}}Od(a){if("entered-fullscreen"===a)b.Tb(!0),H(this.oa);else if("exited-fullscreen"===a)b.Tb(!1),H(this.oa);else if("object"===typeof a){const c=a.type;"directory-handles"!==c&&("wrapper-init-response"===c?(this.vd(a),this.vd=null):"extension-message"===c?this.rb("runtime","wrapper-extension-message",a):console.warn("Unknown wrapper message: ",a))}else console.warn("Unknown wrapper message: ",a)}nf(a){this.Ja({type:"extension-message",componentId:a.componentId,
messageId:a.messageId,params:a.params||[],asyncId:a.asyncId})}Ja(a){this.qa()?window.chrome.webview.postMessage(JSON.stringify(a)):"macos-wkwebview"===this.u&&window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a))}rf(){window.moveTo=(a,c)=>{this.Ja({type:"set-window-position",windowX:Math.ceil(a),windowY:Math.ceil(c)})};window.resizeTo=(a,c)=>{this.Ja({type:"set-window-size",windowWidth:Math.ceil(a),windowHeight:Math.ceil(c)})}}df(){return this.qa()?new Promise(a=>{this.vd=a;this.Ja({type:"wrapper-init"})}):
Promise.resolve()}async We(){const a=[];for(const [c,d]of Object.entries(this.ua))a.push(this.Ve(c,d));await Promise.all(a)}async Ve(a,c){if("object"===typeof c)this.ua[a]=new Blob([c.str],{type:c.type}),this.bc[a]=c.str;else{let d=await this.$e(c);d||(d=this.Ye(c));this.ua[a]=d}}async $e(a){try{return await (await fetch(a)).blob()}catch(c){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
c),null}}Ye(a){a=this.qf(a);return this.Ue(a.data,a.Ef)}qf(a){var c=a.indexOf(",");if(0>c)throw new URIError("expected comma in data: uri");var d=a.substring(c+1);c=a.substring(5,c).split(";");a=c[0]||"";const e=c[2];d="base64"===c[1]||"base64"===e?atob(d):decodeURIComponent(d);return{Ef:a,data:d}}Ue(a,c){var d=a.length;let e=d>>2,f=new Uint8Array(d),g=new Uint32Array(f.buffer,0,e),h,k;for(k=h=0;h<e;++h)g[h]=a.charCodeAt(k++)|a.charCodeAt(k++)<<8|a.charCodeAt(k++)<<16|a.charCodeAt(k++)<<24;for(d&=
3;d--;)f[k]=a.charCodeAt(k),++k;return new Blob([f],{type:c})}};"use strict";const I=self.ya,Da=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),J={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},Ea={dispatchUserScriptEvent:!0},Fa={dispatchRuntimeEvent:!0};function Ga(b){return new Promise((a,c)=>{const d=document.createElement("link");d.onload=()=>a(d);d.onerror=e=>c(e);d.rel="stylesheet";d.href=b;document.head.appendChild(d)})}
function Ha(b){return new Promise((a,c)=>{const d=new Image;d.onload=()=>a(d);d.onerror=e=>c(e);d.src=b})}async function Ia(b){b=URL.createObjectURL(b);try{return await Ha(b)}finally{URL.revokeObjectURL(b)}}function Ja(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const Ka=new Set(["input","textarea","datalist","select"]),La=new Set(["canvas","body","html"]);
function K(b){b.target.tagName&&La.has(b.target.tagName.toLowerCase())&&b.preventDefault()}function Ma(b){b.target.tagName&&b.target.classList.contains("c3htmlwrap")&&b.preventDefault()}function Na(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}
self.C3_GetSvgImageSize=async function(b){b=await Ia(b);if(0<b.width&&0<b.height)return[b.width,b.height];b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const a=b.getBoundingClientRect();document.body.removeChild(b);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(b,a,c,d,e){b=await Ia(b);const f=document.createElement("canvas");f.width=d;f.height=e;f.getContext("2d").drawImage(b,0,0,a,c);return f};
let Oa=!1;document.addEventListener("pause",()=>Oa=!0);document.addEventListener("resume",()=>Oa=!1);function za(b){b.addEventListener("selectstart",K);b.addEventListener("gesturehold",K);b.addEventListener("pointerdown",K)}function Aa(b){b.addEventListener("selectstart",Ma);b.addEventListener("gesturehold",Ma);b.addEventListener("touchstart",Ma)}function Ba(b){b.Yd=!0;b.hd=b.h.ra();b.Bb=b.h.ia()}
function H(b){if(!b.ma){var a=I.ob();a&&"any"!==b.rd&&Pa(b);m(b,"fullscreenchange",{isFullscreen:a,innerWidth:b.ra(),innerHeight:b.ia()})}}async function Qa(b){await Promise.all(b.webfonts.map(async a=>{a=new FontFace(a.name,`url('${a.url}')`);document.fonts.add(a);await a.load()}))}
async function Ra(b){var a=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);a=a?await createImageBitmap(b,a):await createImageBitmap(b);return{imageBitmap:a,transferables:[a]}}async function Sa(b){return await self.C3_GetSvgImageSize(b.blob)}function Ta(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}
function Ua(b){self.setTimeout(()=>{b.Xd=!0},1E3);"cordova"===b.h.u?(document.addEventListener("pause",()=>Va(b,!0)),document.addEventListener("resume",()=>Va(b,!1))):document.addEventListener("visibilitychange",()=>Va(b,"hidden"===document.visibilityState));b.hc=!("hidden"!==document.visibilityState&&!Oa);return{isSuspended:b.hc}}
function Wa(b){b.Sd||(b.Sd=!0,window.addEventListener("deviceorientation",a=>{b.ma||m(b,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},J)}),window.addEventListener("deviceorientationabsolute",a=>{b.ma||m(b,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},J)}))}
function Xa(b){b.Rd||(b.Rd=!0,window.addEventListener("devicemotion",a=>{if(!b.ma){var c=null,d=a.acceleration;d&&(c={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=a.accelerationIncludingGravity;e&&(d={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});m(b,"devicemotion",{acceleration:c,accelerationIncludingGravity:d,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},J)}}))}async function Ya(b){await Ga(b.url)}
function Za(b,a){b.$d=a.message;-1===b.Xc&&(b.Xc=setTimeout(()=>{b.Xc=-1;const c=document.getElementById("exportToVideoMessage");c&&(c.textContent=b.$d)},250))}function $a(b,a){console.warn("[Construct] Fullscreen request failed: ",a);m(b,"fullscreenerror",{isFullscreen:I.ob(),innerWidth:b.ra(),innerHeight:b.ia()})}
function Va(b,a){b.hc!==a&&((b.hc=a)?b.h.Ic():b.h.Rc(),m(b,"visibilitychange",{hidden:a}),!a&&b.h.pb()&&(b=()=>{document.scrollingElement.scrollTop=0;document.scrollingElement.scrollLeft=0},setTimeout(b,50),setTimeout(b,100),setTimeout(b,250),setTimeout(b,500)))}
function ab(b,a,c){"Backspace"===c.key&&K(c);"nwjs"===b.h.u&&"u"===c.key&&(c.ctrlKey||c.metaKey)&&c.preventDefault();if(!b.ma){var d=Da.get(c.code)||c.code;n(b,a,{code:d,key:c.key,which:c.which,repeat:c.repeat,altKey:c.altKey,ctrlKey:c.ctrlKey,metaKey:c.metaKey,shiftKey:c.shiftKey,timeStamp:c.timeStamp},J)}}
function L(b,a,c,d){b.ma||c.sourceCapabilities&&c.sourceCapabilities.firesTouchEvents||c.originalEvent&&c.originalEvent.sourceCapabilities&&c.originalEvent.sourceCapabilities.firesTouchEvents||n(b,a,{button:c.button,buttons:c.buttons,clientX:c.clientX,clientY:c.clientY+b.Fa,pageX:c.pageX,pageY:c.pageY+b.Fa,movementX:c.movementX||0,movementY:c.movementY||0,timeStamp:c.timeStamp},d)}
function M(b,a,c){if(!b.ma){var d=0;"mouse"===c.pointerType&&(d=b.kd);n(b,a,{pointerId:c.pointerId,pointerType:c.pointerType,button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.Fa,pageX:c.pageX,pageY:c.pageY+b.Fa,movementX:c.movementX||0,movementY:c.movementY||0,width:c.width||0,height:c.height||0,pressure:c.pressure||0,tangentialPressure:c.tangentialPressure||0,tiltX:c.tiltX||0,tiltY:c.tiltY||0,twist:c.twist||0,timeStamp:c.timeStamp},J);"mouse"===c.pointerType&&
(b.kd=c.buttons)}}function bb(b,a,c){document.body.style.position="";document.body.style.overflow="";document.body.style.transform="";b.Fa=0;if(0<c){var d=document.activeElement;d&&(d=d.getBoundingClientRect(),a=(d.top+d.bottom)/2-(a-c)/2,a>c&&(a=c),0>a&&(a=0),0<a&&(document.body.style.position="absolute",document.body.style.overflow="visible",document.body.style.transform=`translateY(${-a}px)`,b.Fa=a))}}
function cb(b,a,c,d){const e=b.ra(),f=b.ia();b.fb=-1;e!=a||f!=c?m(b,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:I.ob(),cssDisplayMode:b.h.zc()}):10>d&&db(b,e,f,d+1)}function db(b,a,c,d){-1!==b.fb&&clearTimeout(b.fb);b.fb=setTimeout(()=>cb(b,a,c,d),48)}
function Pa(b){b=b.rd;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}function eb(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}
I.ib(class extends self.kb{constructor(b){super(b,"runtime");this.Yd=!1;this.fb=-1;this.rd="any";this.hc=this.Rd=this.Sd=!1;this.nc=document.createElement("div");this.nc.className="c3-screen-reader-text";this.nc.setAttribute("aria-live","polite");document.body.appendChild(this.nc);this.Na=null;this.ma=!1;this.$d="";this.Xc=-1;this.Xd=!1;this.hd=b.ra();this.Bb=b.ia();this.Fa=this.Lb=0;b.B("runtime","invoke-download",c=>{const d=c.url;c=c.filename;const e=document.createElement("a"),f=document.body;
e.textContent=c;e.href=d;e.download=c;f.appendChild(e);e.click();f.removeChild(e)});b.B("runtime","load-webfonts",c=>Qa(c));b.B("runtime","raster-svg-image",c=>Ra(c));b.B("runtime","get-svg-image-size",c=>Sa(c));b.B("runtime","set-target-orientation",c=>{this.rd=c.targetOrientation});b.B("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});b.B("runtime","post-to-debugger",c=>Ta(c));b.B("runtime","go-to-script",c=>Ta(c));b.B("runtime","before-start-ticking",()=>Ua(this));b.B("runtime",
"debug-highlight",c=>{if(c.show){this.Na||(this.Na=document.createElement("div"),this.Na.id="inspectOutline",document.body.appendChild(this.Na));var d=this.Na;d.style.display="";d.style.left=c.left-1+"px";d.style.top=c.top-1+"px";d.style.width=c.width+2+"px";d.style.height=c.height+2+"px";d.textContent=c.name}else this.Na&&(this.Na.style.display="none")});b.B("runtime","enable-device-orientation",()=>Wa(this));b.B("runtime","enable-device-motion",()=>Xa(this));b.B("runtime","add-stylesheet",c=>Ya(c));
b.B("runtime","script-create-worker",c=>{const d=c.port2;(new Worker(c.url,c.opts)).postMessage({type:"construct-worker-init",port2:d},[d])});b.B("runtime","alert",c=>this.Nc(c));b.B("runtime","screen-reader-text",c=>{var d=c.type;"create"===d?(d=document.createElement("p"),d.id="c3-sr-"+c.id,d.textContent=c.text,this.nc.appendChild(d)):"update"===d?(d=document.getElementById("c3-sr-"+c.id))?d.textContent=c.text:console.warn(`[Construct] Missing screen reader text with id ${c.id}`):"release"===d?
(d=document.getElementById("c3-sr-"+c.id))?d.remove():console.warn(`[Construct] Missing screen reader text with id ${c.id}`):console.warn(`[Construct] Unknown screen reader text update '${d}'`)});b.B("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});b.B("runtime","set-exporting-to-video",c=>{this.ma=!0;const d=document.createElement("h1");d.id="exportToVideoMessage";d.textContent=c.message;document.body.prepend(d);document.body.classList.add("exportingToVideo");
this.h.Ed().style.display="";this.h.Se(c.duration)});b.B("runtime","export-to-video-progress",c=>Za(this,c));b.B("runtime","exported-to-video",c=>{window.Af({type:"exported-video",arrayBuffer:c.arrayBuffer,contentType:c.contentType,time:c.time})});b.B("runtime","exported-to-image-sequence",c=>{window.Af({type:"exported-image-sequence",blobArr:c.blobArr,time:c.time,gif:c.gif})});const a=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",c=>{const d=c.target;a.has(d.tagName.toLowerCase())||
Ja(d)||c.preventDefault()});window.addEventListener("selectstart",K);window.addEventListener("gesturehold",K);window.addEventListener("touchstart",K,{passive:!1});window.addEventListener("pointerdown",K,{passive:!1});this.kd=0;window.addEventListener("mousedown",c=>{1===c.button&&c.preventDefault()});window.addEventListener("mousewheel",Na,{passive:!1});window.addEventListener("wheel",Na,{passive:!1});window.addEventListener("resize",()=>{a:{if(!this.ma&&this.Yd){var c=this.ra();var d=this.ia();if(this.h.Dc()){if(this.Xd){if(this.hd===
c&&d<this.Bb){this.Lb=this.Bb-d;bb(this,this.Bb,this.Lb);c=void 0;break a}0<this.Lb&&(this.Lb=0,bb(this,d,this.Lb))}this.hd=c;this.Bb=d}m(this,"window-resize",{innerWidth:c,innerHeight:d,devicePixelRatio:window.devicePixelRatio,isFullscreen:I.ob(),cssDisplayMode:this.h.zc()});this.h.pb()&&(-1!==this.fb&&clearTimeout(this.fb),cb(this,c,d,0))}c=void 0}return c});window.addEventListener("fullscreenchange",()=>H(this));window.addEventListener("webkitfullscreenchange",()=>H(this));window.addEventListener("mozfullscreenchange",
()=>H(this));window.addEventListener("fullscreenerror",c=>$a(this,c));window.addEventListener("webkitfullscreenerror",c=>$a(this,c));window.addEventListener("mozfullscreenerror",c=>$a(this,c));if(b.pb()){let c=Infinity;window.visualViewport.addEventListener("resize",()=>{const d=window.visualViewport.height;d>c&&(document.scrollingElement.scrollTop=0,document.scrollingElement.scrollLeft=0);c=d});document.documentElement.setAttribute("ioswebview","")}this.Za=new Set;this.dc=new WeakSet;this.Ba=!1}tc(){window.addEventListener("focus",
()=>{m(this,"window-focus",null,Fa)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(c){a=!1}m(this,"window-blur",{parentHasFocus:a},Fa);this.kd=0});window.addEventListener("focusin",a=>{a=a.target;(Ka.has(a.tagName.toLowerCase())||Ja(a))&&m(this,"keyboard-blur",null,Fa)});window.addEventListener("keydown",a=>ab(this,"keydown",a));window.addEventListener("keyup",a=>ab(this,"keyup",a));window.addEventListener("mousedown",a=>L(this,"mousedown",a,
Ea));window.addEventListener("mousemove",a=>L(this,"mousemove",a,Ea));window.addEventListener("mouseup",a=>L(this,"mouseup",a,Ea));window.addEventListener("dblclick",a=>L(this,"dblclick",a,J));window.addEventListener("wheel",a=>{this.ma||m(this,"wheel",{clientX:a.clientX,clientY:a.clientY+this.Fa,pageX:a.pageX,pageY:a.pageY+this.Fa,deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},J)});window.addEventListener("pointerdown",a=>{window!==window.top&&window.focus();
eb(a.target)&&document.activeElement&&!eb(document.activeElement)&&document.activeElement.blur();M(this,"pointerdown",a)});this.h.ba&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?window.addEventListener("pointerrawupdate",a=>{M(this,"pointermove",a)}):window.addEventListener("pointermove",a=>M(this,"pointermove",a));window.addEventListener("pointerup",a=>M(this,"pointerup",a));window.addEventListener("pointercancel",a=>M(this,"pointercancel",a));const b=()=>this.Qc();window.addEventListener("pointerup",
b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",b,!0);window.addEventListener("keydown",b,!0);window.addEventListener("gamepadconnected",b,!0);this.h.Ne()&&!this.h.Dc()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{bb(this,this.ia(),navigator.virtualKeyboard.boundingRect.height)}));this.h.pb()&&(document.scrollingElement.scrollTop=0,document.scrollingElement.scrollLeft=0)}ra(){return this.h.ra()}ia(){return this.h.ia()}Qc(){var b=
[...this.Za];this.Za.clear();if(!this.Ba)for(const a of b)(b=a.play())&&b.catch(()=>{this.dc.has(a)||this.Za.add(a)})}ca(b){if("function"!==typeof b.play)throw Error("missing play function");this.dc.delete(b);let a;try{a=b.play()}catch(c){this.Za.add(b);return}a&&a.catch(()=>{this.dc.has(b)||this.Za.add(b)})}ha(b){this.Za.delete(b);this.dc.add(b)}Qb(b){this.Ba=!!b}Nc(b){alert(b.message)}});"use strict";
async function wa(b){if(b.tf)throw Error("already initialised");b.tf=!0;var a=b.Da.Kc(("playable-ad"===b.Da.u?b.Da.eb:"")+"dispatchworker.js");b.Wc=await b.Da.vc(a,b.tb,{name:"DispatchWorker"});a=new MessageChannel;b.bd=a.port1;b.Wc.postMessage({type:"_init","in-port":a.port2},[a.port2]);b.md=await Ca(b)}function xa(b){return[b.bd,b.md]}
async function Ca(b){const a=b.fe.length;var c=b.Da.Kc(("playable-ad"===b.Da.u?b.Da.eb:"")+"jobworker.js");c=await b.Da.vc(c,b.tb,{name:"JobWorker"+a});const d=new MessageChannel,e=new MessageChannel;b.Wc.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);c.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":e.port2},[d.port2,e.port2]);b.fe.push(c);return e.port1}
self.Qe=class{constructor(b){this.Da=b;this.tb=b.aa;this.tb="preview"===b.u?this.tb+"workers/":this.tb+b.eb;this.vf=Math.min(navigator.hardwareConcurrency||2,16);this.Wc=null;this.fe=[];this.md=this.bd=null}};"use strict";window.C3_Is_Supported&&(window.c3_runtimeInterface=new self.ya({Jf:!0,Kf:"workermain.js",gb:["scripts/c3runtime.js"],rc:[],wd:"",Gf:"scripts/",sc:[],ue:"html5"}));"use strict";let N=null,fb=null;
window.addEventListener("beforeinstallprompt",b=>{b.preventDefault();N=b;fb&&m(fb,"install-available");return!1});function gb(){}function hb(b){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(a=>m(b,"sw-message",a.data))}
function ib(b){b=b.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}async function lb(){if(!N)return{result:"unavailable"};try{return N.prompt(),{result:(await N.userChoice).outcome}}catch(b){return console.error("[Construct] Requesting install failed: ",b),{result:"failed"}}}
self.ya.ib(class extends self.kb{constructor(b){super(b,"browser");this.u="";v(this,[["get-initial-state",a=>{this.u=a.exportType;return{location:location.toString(),isOnline:!!navigator.onLine,referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,isConstructArcade:"undefined"!==typeof window.is_scirra_arcade}}],["ready-for-sw-messages",()=>
hb(this)],["alert",a=>this.Nc(a)],["close",()=>{navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}],["set-focus",a=>this.Pc(a)],["vibrate",a=>{navigator.vibrate&&navigator.vibrate(a.pattern)}],["lock-orientation",a=>ib(a)],["unlock-orientation",()=>{try{screen.orientation&&screen.orientation.unlock?screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?
screen.webkitUnlockOrientation():screen.mozUnlockOrientation?screen.mozUnlockOrientation():screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(a){}}],["navigate",a=>{var c=a.type;if("back"===c)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.history.back();else if("forward"===c)window.history.forward();else if("reload"===c)location.reload();else if("url"===c){c=a.url;const d=a.target;a=a.exportType;self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(c,
"_system"):"preview"===a||this.h.qa()?window.open(c,"_blank"):this.Pf||(2===d?window.top.location=c:1===d?window.parent.location=c:window.location=c)}else"new-window"===c&&(c=a.url,a=a.tag,self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(c,"_system"):window.open(c,a))}],["request-fullscreen",a=>{if(this.h.qa()||"macos-wkwebview"===this.u)self.ya.Tb(!0),this.h.Ja({type:"set-fullscreen",fullscreen:!0});else{const c={navigationUI:"auto"};a=a.navUI;1===a?c.navigationUI="hide":2===
a&&(c.navigationUI="show");a=document.documentElement;let d;a.requestFullscreen?d=a.requestFullscreen(c):a.mozRequestFullScreen?d=a.mozRequestFullScreen(c):a.msRequestFullscreen?d=a.msRequestFullscreen(c):a.webkitRequestFullScreen&&(d="undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?a.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):a.webkitRequestFullScreen());d instanceof Promise&&d.catch(gb)}}],["exit-fullscreen",()=>{if(this.h.qa()||"macos-wkwebview"===this.u)self.ya.Tb(!1),this.h.Ja({type:"set-fullscreen",
fullscreen:!1});else{let a;document.exitFullscreen?a=document.exitFullscreen():document.mozCancelFullScreen?a=document.mozCancelFullScreen():document.msExitFullscreen?a=document.msExitFullscreen():document.webkitCancelFullScreen&&(a=document.webkitCancelFullScreen());a instanceof Promise&&a.catch(gb)}}],["set-hash",a=>{location.hash=a.hash}],["set-document-css-style",a=>{const c=a.prop,d=a.value;var e=a.selector;a=a["is-all"];try{if(e)if(a)var f=Array.from(document.querySelectorAll(e));else{var g=
document.querySelector(e);f=g?[g]:[]}else f=[document.documentElement];e=f;for(const h of e)c.startsWith("--")?h.style.setProperty(c,d):h.style[c]=d}catch(h){console.warn("[Browser] Failed to set style: ",h)}}],["get-document-css-style",a=>{{const d=a.prop;a=a.selector;try{const e=document.querySelector(a);var c=e?{isOk:!0,result:window.getComputedStyle(e).getPropertyValue(d)}:{isOk:!1}}catch(e){console.warn("[Browser] Failed to get style: ",e),c={isOk:!1}}}return c}],["set-window-size",a=>{window.resizeTo(a.windowWidth,
a.windowHeight)}],["set-window-position",a=>{window.moveTo(a.windowX,a.windowY)}],["request-install",()=>lb()],["set-warn-on-close",a=>{a.enabled?window.addEventListener("beforeunload",this.Td):window.removeEventListener("beforeunload",this.Td)}]]);window.addEventListener("online",()=>{m(this,"online-state",{isOnline:!0})});window.addEventListener("offline",()=>{m(this,"online-state",{isOnline:!1})});window.addEventListener("hashchange",()=>{m(this,"hashchange",{location:location.toString()})});this.Td=
a=>a.preventDefault();document.addEventListener("backbutton",()=>{m(this,"backbutton")})}tc(){N?m(this,"install-available"):fb=this;window.addEventListener("appinstalled",()=>{m(this,"app-installed")})}Nc(b){alert(b.message)}Pc(b){b=b.isFocus;if("nwjs"===this.u){const a="nwjs"===this.u?nw.Window.get():null;b?a.focus():a.blur()}else b?window.focus():window.blur()}});"use strict";
self.ya.ib(class extends self.kb{constructor(b){super(b,"mouse");v(this,[["cursor",a=>{document.documentElement.style.cursor=a}],["request-pointer-lock",()=>{this.h.Ed().requestPointerLock()}],["release-pointer-lock",()=>{document.exitPointerLock()}]]);document.addEventListener("pointerlockchange",()=>{m(this,"pointer-lock-change",{"has-pointer-lock":!!document.pointerLockElement})});document.addEventListener("pointerlockerror",()=>{m(this,"pointer-lock-error",{"has-pointer-lock":!!document.pointerLockElement})})}});
"use strict";const mb=180/Math.PI;
async function nb(b,a){a.usePlayMusicAsSoundWorkaround&&(b.jc=!0);b.sd=a.timeScaleMode;b.ke=["equalpower","HRTF","soundfield"][a.panningModel];b.Wd=["linear","inverse","exponential"][a.distanceModel];b.le=a.refDistance;b.je=a.maxDistance;b.ne=a.rolloffFactor;if(b.h.cd)b.jc=!0,b.g=new OfflineAudioContext({numberOfChannels:2,sampleRate:48E3,length:Math.ceil(48E3*b.h.Zd)});else{var c={latencyHint:a.latencyHint};b.qe||(c.sampleRate=48E3);if("undefined"!==typeof AudioContext)b.g=new AudioContext(c);else if("undefined"!==
typeof webkitAudioContext)b.g=new webkitAudioContext(c);else throw Error("Web Audio API not supported");ob(b);b.g.onstatechange=()=>{"running"!==b.g.state&&ob(b);m(b,"audiocontext-state",{audioContextState:b.g.state})}}b.Ua=b.g.createGain();b.Ua.connect(b.g.destination);c=a.listenerPos;b.$[0]=c[0];b.$[1]=c[1];b.$[2]=c[2];b.g.listener.setPosition(c[0],c[1],c[2]);b.g.listener.setOrientation(...b.da);self.C3_GetAudioContextCurrentTime=()=>b.g.currentTime;try{await Promise.all(a.preloadList.map(d=>O(b,
d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct] Preloading sounds failed: ",d)}return{sampleRate:b.g.sampleRate,audioContextState:b.g.state,outputLatency:b.g.outputLatency||0}}
async function pb(b,a){var c=a.originalUrl,d=a.url;const e=a.type,f=a.isMusic,g=a.tags,h=a.isLooping,k=a.vol,l=a.pos,q=a.panning,r=a.stereoPan;let t=a.off;0<t&&!a.trueClock&&(b.g.getOutputTimestamp?(a=b.g.getOutputTimestamp(),t=t-a.performanceTime/1E3+a.contextTime):t=t-performance.now()/1E3+b.g.currentTime);b.ge=g.slice(0);qb(b,g);try{b.R=await rb(b,c,d,e,g,f);if(q){P(b.R,!0);var u=b.R,da=q.x,G=q.y,Gb=q.z,Hb=q.angle,qa=q.innerAngle,ra=q.outerAngle,sa=q.outerGain;if(u.zb){sb(u,da,G,Gb,Hb);var D=self.jb.Te;
u.va[0]!==D(qa)&&(u.va[0]=D(qa),u.F.coneInnerAngle=D(qa));u.va[1]!==D(ra)&&(u.va[1]=D(ra),u.F.coneOuterAngle=D(ra));u.va[2]!==sa&&(u.va[2]=sa,u.F.coneOuterGain=sa)}q.hasOwnProperty("uid")&&(b.R.ta=q.uid)}else"number"===typeof r&&0!==r?(Q(b.R,!0),tb(b.R,r)):(P(b.R,!1),Q(b.R,!1));b.R.Play(h,k,l,t)}catch(Ib){console.error("[Construct] Audio: error starting playback: ",Ib);return}finally{c=g.join(" ");d=b.Hb.get(c);if(!d)throw Error("expected pending tag");d.xd--;0===d.xd&&(d.resolve(),b.Hb.delete(c))}w(b)}
async function ub(b,a){var c=a.tags;const d=a.vol,e=a.duration;a=a.stopOnEnd;await vb(b,c);for(const h of R(b,c))if(!h.Aa){c=h.G.gain;c.cancelScheduledValues(0);var f=h.v.g.currentTime,g=f+e;c.setValueAtTime(c.value,f);c.linearRampToValueAtTime(d,g);h.Qa=d;h.Xa=g;h.pe=a}S(b)}async function wb(b,a){const c=a.tags;a=a.rate;await vb(b,c);for(const d of R(b,c))d.na!==a&&(d.na=a,d.Ka())}async function xb(b,a){const c=a.tags;a=a.pos;await vb(b,c);for(const d of R(b,c))d.Ec(a)}
async function yb(b,a){const c=a.originalUrl,d=a.url,e=a.type;a=a.isMusic;try{await rb(b,c,d,e,"",a)}catch(f){console.error("[Construct] Audio: error preloading: ",f)}}async function zb(b,a){if(a=await O(b,"",a.url,a.type,a.isMusic,!0))a.l(),a=b.ka.indexOf(a),-1!==a&&b.ka.splice(a,1)}
async function Ab(b,a){const c=a.type;var d=a.hasOwnProperty("tags")?a.tags:[a.tag];const e=a.params;let f;if("convolution"===c)try{f=await O(b,a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(k){console.log("[Construct] Audio: error loading convolution: ",k);return}for(const k of d){if("filter"===c)d=new self.Ae(b,...e);else if("delay"===c)d=new self.ye(b,...e);else if("convolution"===c){var g=d=new self.xe(b,f.ja,...e),h=a.bufferType;g.Ud=a.bufferOriginalUrl;g.Vd=h}else if("flanger"===c)d=
new self.Be(b,...e);else if("phaser"===c)d=new self.De(b,...e);else if("gain"===c)d=new self.Ce(b,...e);else if("stereopan"===c)d=new self.Fe(b,...e);else if("tremolo"===c)d=new self.Ge(b,...e);else if("ringmod"===c)d=new self.Ee(b,...e);else if("distortion"===c)d=new self.ze(b,...e);else if("compressor"===c)d=new self.we(b,...e);else if("analyser"===c)d=new self.ve(b,...e);else throw Error("invalid effect type");g=b;h=k;h=h.toLowerCase();let l=g.la.get(h);l||(l=[],g.la.set(h,l));d.de=l.length;d.qd=
h;l.push(d);Bb(g,h)}Cb(b)}
async function Db(b,a){const c=a.saveLoadMode;if(3!==c){var d=[];for(var e of b.H)e.Ga()&&1===c||!e.Ga()&&2===c?d.push(e):e.l();b.H=d}for(const f of b.la.values())for(const g of f)g.l();b.la.clear();b.pc=a.timeScale;b.Yc=a.gameTime;d=a.listenerPos;b.$[0]=d[0];b.$[1]=d[1];b.$[2]=d[2];b.g.listener.setPosition(d[0],d[1],d[2]);d=a.listenerOrientation;if(Array.isArray(d)){for(e=0;6>e;++e)b.da[e]=d[e];b.g.listener.setOrientation(...b.da)}b.Ba=a.isSilent;b.h.Qb(b.Ba);b.cc=a.masterVolume;b.Ua.gain.value=
b.cc;d=[];for(const f of Object.values(a.effects))d.push(Promise.all(f.map(g=>Ab(b,g))));await Promise.all(d);await Promise.all(a.playing.map(f=>Eb(b,f,c)));S(b)}
async function Fb(b,a){try{const c=b.g.suspend(a.time);b.ce?b.g.resume():(b.g.startRendering().then(d=>{const e=[];for(let f=0,g=d.numberOfChannels;f<g;++f){const h=d.getChannelData(f);e.push(h.buffer)}b.h.rb("runtime","offline-audio-render-completed",{duration:d.duration,length:d.length,numberOfChannels:d.numberOfChannels,sampleRate:d.sampleRate,channelData:e},null,e)}).catch(d=>Jb(d)),b.ce=!0);await c}catch(c){Jb(c)}}
function ob(b){b.Xb||(b.ad=!1,window.addEventListener("pointerup",b.Ea,!0),window.addEventListener("touchend",b.Ea,!0),window.addEventListener("click",b.Ea,!0),window.addEventListener("keydown",b.Ea,!0),b.Xb=!0)}
async function O(b,a,c,d,e,f){for(var g of b.ka)if(g.nb()===c)return await Kb(g),g;if(f)return null;if(e&&(b.jc||b.be)){f=0;for(let h=0,k=b.ka.length;h<k;++h)g=b.ka[h],b.ka[f]=g,g.Ga()?g.l():++f;b.ka.length=f}f="audio/webm; codecs=opus"===d&&!b.qe;e&&f&&(b.be=!0);c=!e||b.jc||f?new self.Je(b,a,c,d,e,f):new self.He(b,a,c,d,e);b.ka.push(c);await Kb(c);b.ie.has(a)||(m(b,"buffer-metadata",{originalUrl:a,duration:c.ga()}),b.ie.add(a));return c}
function Lb(b,a){return b===a||b.normalize().toLowerCase()===a.normalize().toLowerCase()}function Mb(b,a){return(a=b.la.get(a.toLowerCase()))?a[0].N():b.fa()}function Bb(b,a){a=a.toLowerCase();let c=b.fa();var d=b.la.get(a);if(d&&d.length){c=d[0].N();for(let f=0,g=d.length;f<g;++f){var e=d[f];f+1===g?e.U(b.fa()):e.U(d[f+1].N())}}for(const f of Nb(b,a))e=f,d=c,e=e.ea||e.F||e.G,e.disconnect(),e.connect(d);b.Oa&&b.jd===a&&(b.Oa.disconnect(),b.Oa.connect(c))}
function*Nb(b,a){if(a)for(const c of b.H)Lb(0<c.pa.length?c.pa[0]:"",a)&&(yield c);else b.R&&!b.R.O()&&(yield b.R)}function Ob(b,a,c){return c?b.h.sf(a).then(d=>{const e=b.g.createBuffer(1,d.length,48E3);e.getChannelData(0).set(d);return e}):new Promise((d,e)=>{b.g.decodeAudioData(a,d,e)})}function Pb(b,a){let c=0;for(let d=0,e=b.H.length;d<e;++d){const f=b.H[d];b.H[c]=f;f.P===a?f.l():++c}b.H.length=c}
function*R(b,a){if(0<a.length)for(const d of b.H){a:{b=d.pa;var c=a;for(const e of c){c=!1;for(const f of b)if(Lb(f,e)){c=!0;break}if(!c){b=!1;break a}}b=!0}b&&(yield d)}else b.R&&!b.R.O()&&(yield b.R)}async function rb(b,a,c,d,e,f){for(const g of b.H)if(g.nb()===c&&(g.uc()||f))return g.pa=e,g;a=await O(b,a,c,d,f);e="html5"===a.Tc?new self.Ie(a.v,a,e):new self.Ke(a.v,a,e);b.H.push(e);return e}
function qb(b,a){a=a.join(" ");let c=b.Hb.get(a);if(!c){let d=null;c={xd:0,promise:new Promise(e=>d=e),resolve:d};b.Hb.set(a,c)}c.xd++}function vb(b,a){return(b=b.Hb.get((0===a.length?b.ge:a).join(" ")))?b.promise:Promise.resolve()}function S(b){if(0<b.Ta.size)w(b);else for(const a of b.H)if(!a.I&&!a.O()){w(b);break}}function Qb(b,a,c,d){m(b,"trigger",{type:a,tags:c,aiid:d})}function Cb(b){b.dd||(b.dd=!0,Promise.resolve().then(()=>Rb(b)))}
function Rb(b){const a={};for(const [c,d]of b.la)a[c]=d.map(e=>e.mb());m(b,"fxstate",{fxstate:a});b.dd=!1}
async function Eb(b,a,c){if(3!==c){var d=a.bufferOriginalUrl,e=a.bufferUrl,f=a.bufferType,g=a.isMusic,h=a.tags,k=a.isLooping,l=a.volume,q=a.playbackTime;if(!g||1!==c)if(g||2!==c){c=null;try{c=await rb(b,d,e,f,h,g)}catch(r){console.error("[Construct] Audio: error loading audio state: ",r);return}b=c;(d=a.pan)?(P(b,!0),e=b.F,f=d.pos,b.ab[0]=f[0],b.ab[1]=f[1],b.ab[2]=f[2],f=d.orient,b.$a[0]=f[0],b.$a[1]=f[1],b.$a[2]=f[2],e.setPosition(...b.ab),e.setOrientation(...b.$a),b.va[0]=d.cia,b.va[1]=d.coa,b.va[2]=
d.cog,e.coneInnerAngle=d.cia,e.coneOuterAngle=d.coa,e.coneOuterGain=d.cog,b.ta=d.uid):P(b,!1);b=c;d=a.stereoPan;"number"!==typeof d?Q(b,!1):(Q(b,!0),tb(b,d));c.Play(k,l,q,0);a.isPlaying||c.qb();c.Mc(a)}}}function Jb(b){console.error("[Audio] Offline rendering error: ",b)}
self.jb=class extends self.kb{constructor(b){super(b,"audio");this.Ua=this.g=null;this.Xb=this.ad=!1;this.Ea=()=>{if(!this.ad){var a=this.g;"suspended"===a.state&&a.resume&&a.resume();var c=a.createBuffer(1,220,22050),d=a.createBufferSource();d.buffer=c;d.connect(a.destination);d.start(0);"running"===a.state&&this.Xb&&(this.ad=!0,window.removeEventListener("pointerup",this.Ea,!0),window.removeEventListener("touchend",this.Ea,!0),window.removeEventListener("click",this.Ea,!0),window.removeEventListener("keydown",
this.Ea,!0),this.Xb=!1)}};this.ka=[];this.H=[];this.R=null;this.ge=[];this.ie=new Set;this.he=-1;this.Hb=new Map;this.cc=1;this.Ba=!1;this.sd=0;this.pc=1;this.Yc=0;this.ke="HRTF";this.Wd="inverse";this.le=600;this.je=1E4;this.ne=1;this.$=[0,0,0];this.da=[0,0,-1,0,1,0];this.be=this.jc=!1;this.qe=this.h.Oe();this.la=new Map;this.Ta=new Set;this.ce=this.dd=!1;this.jd="";this.Oa=null;self.C3Audio_OnMicrophoneStream=(a,c)=>{this.Oa&&this.Oa.disconnect();this.jd=c.toLowerCase();this.Oa=this.g.createMediaStreamSource(a);
this.Oa.connect(Mb(this,this.jd))};this.Wb=null;self.C3Audio_GetOutputStream=()=>{this.Wb||(this.Wb=this.g.createMediaStreamDestination(),this.Ua.connect(this.Wb));return this.Wb.stream};self.C3Audio_DOMInterface=this;v(this,[["create-audio-context",a=>nb(this,a)],["play",a=>pb(this,a)],["stop",a=>{a=a.tags;for(const c of R(this,a))c.Ha()}],["stop-all",()=>{for(const a of this.H)a.Ha()}],["set-paused",a=>{const c=a.tags;a=a.paused;for(const d of R(this,c))a?d.qb():d.Pb();S(this)}],["set-volume",a=>
{const c=a.tags;a=a.vol;for(const d of R(this,c))T(d,a)}],["fade-volume",a=>ub(this,a)],["set-master-volume",a=>{this.cc=a.vol;this.Ua.gain.value=this.cc}],["set-muted",a=>{const c=a.tags;a=a.isMuted;for(const d of R(this,c))Sb(d,a)}],["set-silent",a=>{this.Ba=a.isSilent;this.h.Qb(this.Ba);for(const c of this.H)c.Ub()}],["set-looping",a=>{const c=a.tags;a=a.isLooping;for(const d of R(this,c))d.Fc(a)}],["set-playback-rate",a=>wb(this,a)],["set-stereo-pan",a=>{const c=a.tags;a=a.p;for(const d of R(this,
c))Q(d,!0),tb(d,a)}],["seek",a=>xb(this,a)],["preload",a=>yb(this,a)],["unload",a=>zb(this,a)],["unload-all",()=>{for(const a of this.ka)a.l();this.ka.length=0}],["set-suspended",a=>{a=a.isSuspended;!a&&this.g.resume&&this.g.resume();for(const c of this.H)c.Gc(a);a&&this.g.suspend&&this.g.suspend()}],["add-effect",a=>Ab(this,a)],["set-effect-param",a=>{var c=a.tags;const d=a.index,e=a.param,f=a.value,g=a.ramp;a=a.time;for(const h of c)c=this.la.get(h.toLowerCase()),!c||0>d||d>=c.length||c[d].Z(e,
f,g,a);Cb(this)}],["remove-effects",a=>{a=a.tags;for(const c of a){a=c.toLowerCase();const d=this.la.get(a);if(!d||!d.length)break;for(const e of d)e.l();this.la.delete(a);Bb(this,a)}}],["tick",a=>{this.pc=a.timeScale;this.Yc=a.gameTime;this.he=a.tickCount;if(0!==this.sd)for(var c of this.H)c.Ka();!(c=a.listenerPos)||this.$[0]===c[0]&&this.$[1]===c[1]&&this.$[2]===c[2]||(this.$[0]=c[0],this.$[1]=c[1],this.$[2]=c[2],this.g.listener.setPosition(c[0],c[1],c[2]));if((c=a.listenerOrientation)&&(this.da[0]!==
c[0]||this.da[1]!==c[1]||this.da[2]!==c[2]||this.da[3]!==c[3]||this.da[4]!==c[4]||this.da[5]!==c[5])){for(let d=0;6>d;++d)this.da[d]=c[d];this.g.listener.setOrientation(...this.da)}for(const d of a.instPans){a=d.uid;for(const e of this.H)e.ta===a&&sb(e,d.x,d.y,d.z,d.angle)}}],["load-state",a=>Db(this,a)],["offline-render-audio",a=>Fb(this,a)],["offline-render-finish",()=>{this.g.resume()}]])}V(){return this.g}fa(){return this.Ua}GetAudioContextExtern(){return this.V()}GetDestinationNodeExtern(){return this.fa()}Ob(){return this.Ba}ca(b){this.h.ca(b)}ha(b){this.h.ha(b)}Ia(){for(var b of this.Ta)b.Ia();
b=this.g.currentTime;for(var a of this.H)a.Ia(b);a=this.H.filter(c=>!c.I&&!c.O()).map(c=>c.mb());m(this,"state",{tickCount:this.he,outputLatency:this.g.outputLatency||0,audioInstances:a,analysers:[...this.Ta].map(c=>({tag:c.qd,index:c.de,peak:c.bb,rms:c.me,binCount:c.m.frequencyBinCount,freqBins:c.ae}))});0===a.length&&0===this.Ta.size&&aa(this)}static Te(b){return b*mb}static Cd(b){return Math.max(Math.min(Math.pow(10,b/20),1),0)}static Re(b){return Math.log(Math.max(Math.min(b,1),0))/Math.log(10)*
20}};self.ya.ib(self.jb);"use strict";function Kb(b){b.ac||(b.ac=b.Lc());return b.ac}self.yd=class{constructor(b,a,c,d,e){this.v=b;this.xf=a;this.Pa=c;this.T=d;this.uf=e;this.Tc="";this.ac=null}l(){this.ac=this.v=null}Lc(){}V(){return this.v.V()}Ac(){return this.xf}nb(){return this.Pa}yc(){return this.T}Ga(){return this.uf}ga(){}};"use strict";
self.He=class extends self.yd{constructor(b,a,c,d,e){super(b,a,c,d,e);this.Tc="html5";this.L=new Audio;this.L.crossOrigin="anonymous";this.L.autoplay=!1;this.L.preload="auto";this.Cb=this.Db=null;this.L.addEventListener("canplaythrough",()=>!0);this.Gb=this.V().createGain();this.Fb=null;this.L.addEventListener("canplay",()=>{this.Db&&(this.Db(),this.Cb=this.Db=null);!this.Fb&&this.L&&(this.Fb=this.V().createMediaElementSource(this.L),this.Fb.connect(this.Gb))});this.onended=null;this.L.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.L.addEventListener("error",f=>{console.error(`[Construct] Audio '${this.Pa}' error: `,f);this.Cb&&(this.Cb(f),this.Cb=this.Db=null)})}l(){Pb(this.v,this);this.Gb.disconnect();this.Gb=null;this.Fb.disconnect();this.Fb=null;this.L&&!this.L.paused&&this.L.pause();this.L=this.onended=null;super.l()}Lc(){return new Promise((b,a)=>{this.Db=b;this.Cb=a;this.L.src=this.Pa})}W(){return this.L}ga(){return this.L.duration}};"use strict";
async function Tb(b){if(b.La)return b.La;var a=b.v.h;if("cordova"===a.u&&a.Fd(b.Pa)&&a.Zb)b.La=await a.Nb(b.Pa);else{a=await fetch(b.Pa);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);b.La=await a.arrayBuffer()}}async function Ub(b){if(b.ja)return b.ja;b.ja=await Ob(b.v,b.La,b.wf);b.La=null}
self.Je=class extends self.yd{constructor(b,a,c,d,e,f){super(b,a,c,d,e);this.Tc="webaudio";this.ja=this.La=null;this.wf=!!f}l(){Pb(this.v,this);this.ja=this.La=null;super.l()}async Lc(){try{await Tb(this),await Ub(this)}catch(b){console.error(`[Construct] Failed to load audio '${this.Pa}': `,b)}}ga(){return this.ja?this.ja.duration:0}};"use strict";let Vb=0;
function P(b,a){a=!!a;b.zb!==a&&(b.zb=a,b.zb?(Q(b,!1),b.F||(b.F=b.V().createPanner(),b.F.panningModel=b.v.ke,b.F.distanceModel=b.v.Wd,b.F.refDistance=b.v.le,b.F.maxDistance=b.v.je,b.F.rolloffFactor=b.v.ne),b.G.disconnect(),b.G.connect(b.F),b.F.connect(b.fa())):(b.F.disconnect(),b.G.disconnect(),b.G.connect(b.fa())))}
function Q(b,a){a=!!a;b.$b!==a&&(b.$b=a,b.$b?(P(b,!1),b.ea=b.V().createStereoPanner(),b.G.disconnect(),b.G.connect(b.ea),b.ea.connect(b.fa())):(b.ea.disconnect(),b.ea=null,b.G.disconnect(),b.G.connect(b.fa())))}function tb(b,a){b.$b&&b.pd!==a&&(b.ea.pan.value=a,b.pd=a)}function T(b,a){b.Qa=a;b.G.gain.cancelScheduledValues(0);b.Xa=-1;b.G.gain.value=b.Bc()}function Sb(b,a){a=!!a;b.Aa!==a&&(b.Aa=a,b.Ub())}
function sb(b,a,c,d,e){if(b.zb){var f=b.ab,g=b.$a,h=Math.cos(e);e=Math.sin(e);if(f[0]!==a||f[1]!==c||f[2]!==d)f[0]=a,f[1]=c,f[2]=d,b.F.setPosition(...f);if(g[0]!==h||g[1]!==e||0!==g[2])g[0]=h,g[1]=e,g[2]=0,b.F.setOrientation(...g)}}function U(b){return b.fd?b.v.Yc:performance.now()/1E3}
self.zd=class{constructor(b,a,c){this.v=b;this.P=a;this.pa=c;this.Vb=Vb++;this.G=this.V().createGain();this.G.connect(this.fa());this.F=null;this.zb=!1;this.ab=[0,0,0];this.$a=[0,0,0];this.va=[0,0,0];this.ea=null;this.$b=!1;this.pd=0;this.I=!0;this.Y=this.wa=this.J=!1;this.Qa=1;this.Aa=!1;this.na=1;b=this.v.sd;this.fd=1===b&&!this.Ga()||2===b;this.Xa=this.ta=-1;this.pe=!1}l(){this.P=this.v=null;this.F&&(this.F.disconnect(),this.F=null);this.ea&&(this.ea.disconnect(),this.ea=null);this.G.disconnect();
this.G=null}V(){return this.v.V()}fa(){return Mb(this.v,0<this.pa.length?this.pa[0]:"")}Ac(){return this.P.Ac()}nb(){return this.P.nb()}yc(){return this.P.yc()}Ga(){return this.P.Ga()}O(){}uc(){}IsPlaying(){return!this.I&&!this.J&&!this.O()}Ra(){}ga(){return this.P.ga()}Play(){}Ha(){}qb(){}Pb(){}Ia(b){-1!==this.Xa&&b>=this.Xa&&(this.Xa=-1,this.pe&&this.Ha(),Qb(this.v,"fade-ended",this.pa,this.Vb))}Bc(){const b=this.Qa;return isFinite(b)?b:0}Ob(){return this.v.Ob()}Ub(){}Fc(){}Ka(){}Ec(){}Gc(){}Cc(){}mb(){var b=
this.Vb,a=this.pa,c=this.ga(),d=-1===this.Xa?this.Qa:this.G.gain.value,e=this.IsPlaying();if(this.F){var f=this.F;f={pos:this.ab,orient:this.$a,cia:f.coneInnerAngle,coa:f.coneOuterAngle,cog:f.coneOuterGain,uid:this.ta}}else f=null;return{aiid:b,tags:a,duration:c,volume:d,isPlaying:e,playbackTime:this.Ra(),playbackRate:this.na,uid:this.ta,bufferOriginalUrl:this.Ac(),bufferUrl:"",bufferType:this.yc(),isMusic:this.Ga(),isLooping:this.Y,isMuted:this.Aa,resumePosition:this.Cc(),pan:f,stereoPan:this.ea?
this.pd:null}}Mc(b){var a=b.playbackRate;this.na!==a&&(this.na=a,this.Ka());Sb(this,b.isMuted)}};"use strict";
self.Ie=class extends self.zd{constructor(b,a,c){super(b,a,c);this.P.Gb.connect(this.G);this.P.onended=()=>this.Oc()}l(){this.Ha();this.P.Gb.disconnect();super.l()}W(){return this.P.W()}Oc(){this.I=!0;this.ta=-1;Qb(this.v,"ended",this.pa,this.Vb)}O(){return this.W().ended}uc(){return this.I?!0:this.O()}Ra(){let b=this.W().currentTime;this.Y||(b=Math.min(b,this.ga()));return b}Play(b,a,c){const d=this.W();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==b&&(d.loop=b);T(this,a);this.Aa=!1;d.muted&&(d.muted=
!1);if(d.currentTime!==c)try{d.currentTime=c}catch(e){console.warn(`[Construct] Exception seeking audio '${this.P.nb()}' to position '${c}': `,e)}this.v.ca(d);this.J=this.I=!1;this.Y=b;this.na=1}Ha(){const b=this.W();b.paused||b.pause();this.v.ha(b);this.I=!0;this.J=!1;this.ta=-1}qb(){if(!(this.J||this.I||this.O())){var b=this.W();b.paused||b.pause();this.v.ha(b);this.J=!0}}Pb(){!this.J||this.I||this.O()||(this.v.ca(this.W()),this.J=!1)}Ub(){this.W().muted=this.Aa||this.Ob()}Fc(b){b=!!b;this.Y!==
b&&(this.Y=b,this.W().loop=b)}Ka(){let b=this.na;this.fd&&(b*=this.v.pc);try{this.W().playbackRate=b}catch(a){console.warn(`[Construct] Unable to set playback rate '${b}':`,a)}}Ec(b){if(!this.I&&!this.O())try{this.W().currentTime=b}catch(a){console.warn(`[Construct] Error seeking audio to '${b}': `,a)}}Cc(){return this.Ra()}Gc(b){b?this.IsPlaying()?(this.W().pause(),this.wa=!0):this.wa=!1:this.wa&&(this.v.ca(this.W()),this.wa=!1)}};"use strict";
function V(b){b.s&&(b.s.onended=null,b.s.disconnect(),b.s.buffer=null);b.s=null;b.sb=null}
self.Ke=class extends self.zd{constructor(b,a,c){super(b,a,c);this.s=null;this.fc=d=>this.Oc(d);this.$c=!0;this.sb=null;this.S=this.ic=this.kc=0;this.ld=1}l(){this.Ha();V(this);this.fc=null;super.l()}Oc(b){this.J||this.wa||b.target!==this.sb||(this.I=this.$c=!0,this.ta=-1,V(this),Qb(this.v,"ended",this.pa,this.Vb))}O(){return!this.I&&this.s&&this.s.loop||this.J?!1:this.$c}uc(){return!this.s||this.I?!0:this.O()}Ra(){let b;b=this.J?this.S:this.ic+(U(this)-this.kc)*this.na;this.Y||(b=Math.min(b,this.ga()));
return b}Play(b,a,c,d){this.Aa=!1;this.ld=1;T(this,a);V(this);this.s=this.V().createBufferSource();this.s.buffer=this.P.ja;this.s.connect(this.G);this.sb=this.s;this.s.onended=this.fc;this.s.loop=b;this.s.start(d,c);this.J=this.I=this.$c=!1;this.Y=b;this.na=1;this.kc=U(this);this.ic=c}Ha(){if(this.s)try{this.s.stop(0)}catch(b){}this.I=!0;this.J=!1;this.ta=-1}qb(){this.J||this.I||this.O()||(this.S=this.Ra(),this.Y&&(this.S%=this.ga()),this.J=!0,this.s.stop(0))}Pb(){!this.J||this.I||this.O()||(V(this),
this.s=this.V().createBufferSource(),this.s.buffer=this.P.ja,this.s.connect(this.G),this.sb=this.s,this.s.onended=this.fc,this.s.loop=this.Y,T(this,this.Qa),this.Ka(),this.s.start(0,this.S),this.kc=U(this),this.ic=this.S,this.J=!1)}Bc(){return super.Bc()*this.ld}Ub(){this.ld=this.Aa||this.Ob()?0:1;T(this,this.Qa)}Fc(b){b=!!b;this.Y!==b&&(this.Y=b,this.s&&(this.s.loop=b))}Ka(){let b=this.na;this.fd&&(b*=this.v.pc);this.s&&(this.s.playbackRate.value=b)}Ec(b){this.I||this.O()||(this.J?this.S=b:(this.qb(),
this.S=b,this.Pb()))}Cc(){return this.S}Gc(b){b?this.IsPlaying()?(this.wa=!0,this.S=this.Ra(),this.Y&&(this.S%=this.ga()),this.s.stop(0)):this.wa=!1:this.wa&&(V(this),this.s=this.V().createBufferSource(),this.s.buffer=this.P.ja,this.s.connect(this.G),this.sb=this.s,this.s.onended=this.fc,this.s.loop=this.Y,T(this,this.Qa),this.Ka(),this.s.start(0,this.S),this.kc=U(this),this.ic=this.S,this.wa=!1)}Mc(b){super.Mc(b);this.S=b.resumePosition}};"use strict";function W(b){return b.g.createGain()}
function X(b,a,c,d,e){a.cancelScheduledValues(0);if(0===e)a.value=c;else switch(b=b.g.currentTime,e+=b,d){case 0:a.setValueAtTime(c,e);break;case 1:a.setValueAtTime(a.value,b);a.linearRampToValueAtTime(c,e);break;case 2:a.setValueAtTime(a.value,b),a.exponentialRampToValueAtTime(c,e)}}class Y{constructor(b){this.v=b;this.g=b.V();this.de=-1;this.T=this.qd="";this.o=null}l(){this.g=null}N(){}U(){}mb(){return{type:this.T,tag:this.qd,params:this.o}}}
self.Ae=class extends Y{constructor(b,a,c,d,e,f,g){super(b);this.T="filter";this.o=[a,c,d,e,f,g];this.A=W(this);this.j=W(this);this.j.gain.value=g;this.i=W(this);this.i.gain.value=1-g;this.D=this.g.createBiquadFilter();this.D.type=a;this.D.frequency.value=c;this.D.detune.value=d;this.D.Q.value=e;this.D.gain.vlaue=f;this.A.connect(this.D);this.A.connect(this.i);this.D.connect(this.j)}l(){this.A.disconnect();this.D.disconnect();this.j.disconnect();this.i.disconnect();super.l()}U(b){this.j.disconnect();
this.j.connect(b);this.i.disconnect();this.i.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[5]=a;X(this,this.j.gain,a,c,d);X(this,this.i.gain,1-a,c,d);break;case 1:this.o[1]=a;X(this,this.D.frequency,a,c,d);break;case 2:this.o[2]=a;X(this,this.D.detune,a,c,d);break;case 3:this.o[3]=a;X(this,this.D.Q,a,c,d);break;case 4:this.o[4]=a,X(this,this.D.gain,a,c,d)}}};
self.ye=class extends Y{constructor(b,a,c,d){super(b);this.T="delay";this.o=[a,c,d];this.A=W(this);this.j=W(this);this.j.gain.value=d;this.i=W(this);this.i.gain.value=1-d;this.Eb=W(this);this.X=this.g.createDelay(a);this.X.delayTime.value=a;this.wb=W(this);this.wb.gain.value=c;this.A.connect(this.Eb);this.A.connect(this.i);this.Eb.connect(this.j);this.Eb.connect(this.X);this.X.connect(this.wb);this.wb.connect(this.Eb)}l(){this.A.disconnect();this.j.disconnect();this.i.disconnect();this.Eb.disconnect();
this.X.disconnect();this.wb.disconnect();super.l()}U(b){this.j.disconnect();this.j.connect(b);this.i.disconnect();this.i.connect(b)}N(){return this.A}Z(b,a,c,d){const e=self.jb.Cd;switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[2]=a;X(this,this.j.gain,a,c,d);X(this,this.i.gain,1-a,c,d);break;case 4:this.o[1]=e(a);X(this,this.wb.gain,e(a),c,d);break;case 5:this.o[0]=a,X(this,this.X.delayTime,a,c,d)}}};
self.xe=class extends Y{constructor(b,a,c,d){super(b);this.T="convolution";this.o=[c,d];this.Vd=this.Ud="";this.A=W(this);this.j=W(this);this.j.gain.value=d;this.i=W(this);this.i.gain.value=1-d;this.vb=this.g.createConvolver();this.vb.normalize=c;this.vb.buffer=a;this.A.connect(this.vb);this.A.connect(this.i);this.vb.connect(this.j)}l(){this.A.disconnect();this.vb.disconnect();this.j.disconnect();this.i.disconnect();super.l()}U(b){this.j.disconnect();this.j.connect(b);this.i.disconnect();this.i.connect(b)}N(){return this.A}Z(b,
a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.o[1]=a,X(this,this.j.gain,a,c,d),X(this,this.i.gain,1-a,c,d)}}mb(){const b=super.mb();b.bufferOriginalUrl=this.Ud;b.bufferUrl="";b.bufferType=this.Vd;return b}};
self.Be=class extends Y{constructor(b,a,c,d,e,f){super(b);this.T="flanger";this.o=[a,c,d,e,f];this.A=W(this);this.i=W(this);this.i.gain.value=1-f/2;this.j=W(this);this.j.gain.value=f/2;this.xb=W(this);this.xb.gain.value=e;this.X=this.g.createDelay(a+c);this.X.delayTime.value=a;this.C=this.g.createOscillator();this.C.frequency.value=d;this.K=W(this);this.K.gain.value=c;this.A.connect(this.X);this.A.connect(this.i);this.X.connect(this.j);this.X.connect(this.xb);this.xb.connect(this.X);this.C.connect(this.K);
this.K.connect(this.X.delayTime);this.C.start(0)}l(){this.C.stop(0);this.A.disconnect();this.X.disconnect();this.C.disconnect();this.K.disconnect();this.i.disconnect();this.j.disconnect();this.xb.disconnect();super.l()}U(b){this.j.disconnect();this.j.connect(b);this.i.disconnect();this.i.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[4]=a;X(this,this.j.gain,a/2,c,d);X(this,this.i.gain,1-a/2,c,d);break;case 6:this.o[1]=a/1E3;X(this,this.K.gain,a/1E3,
c,d);break;case 7:this.o[2]=a;X(this,this.C.frequency,a,c,d);break;case 8:this.o[3]=a/100,X(this,this.xb.gain,a/100,c,d)}}};
self.De=class extends Y{constructor(b,a,c,d,e,f,g){super(b);this.T="phaser";this.o=[a,c,d,e,f,g];this.A=W(this);this.i=W(this);this.i.gain.value=1-g/2;this.j=W(this);this.j.gain.value=g/2;this.D=this.g.createBiquadFilter();this.D.type="allpass";this.D.frequency.value=a;this.D.detune.value=c;this.D.Q.value=d;this.C=this.g.createOscillator();this.C.frequency.value=f;this.K=W(this);this.K.gain.value=e;this.A.connect(this.D);this.A.connect(this.i);this.D.connect(this.j);this.C.connect(this.K);this.K.connect(this.D.frequency);
this.C.start(0)}l(){this.C.stop(0);this.A.disconnect();this.D.disconnect();this.C.disconnect();this.K.disconnect();this.i.disconnect();this.j.disconnect();super.l()}U(b){this.j.disconnect();this.j.connect(b);this.i.disconnect();this.i.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[5]=a;X(this,this.j.gain,a/2,c,d);X(this,this.i.gain,1-a/2,c,d);break;case 1:this.o[0]=a;X(this,this.D.frequency,a,c,d);break;case 2:this.o[1]=a;X(this,this.D.detune,a,c,d);
break;case 3:this.o[2]=a;X(this,this.D.Q,a,c,d);break;case 6:this.o[3]=a;X(this,this.K.gain,a,c,d);break;case 7:this.o[4]=a,X(this,this.C.frequency,a,c,d)}}};self.Ce=class extends Y{constructor(b,a){super(b);this.T="gain";this.o=[a];this.m=W(this);this.m.gain.value=a}l(){this.m.disconnect();super.l()}U(b){this.m.disconnect();this.m.connect(b)}N(){return this.m}Z(b,a,c,d){const e=self.jb.Cd;switch(b){case 4:this.o[0]=e(a),X(this,this.m.gain,e(a),c,d)}}};
self.Fe=class extends Y{constructor(b,a){super(b);this.T="stereopan";this.o=[a];this.m=this.g.createStereoPanner();this.m.pan.value=a}l(){this.m.disconnect();super.l()}U(b){this.m.disconnect();this.m.connect(b)}N(){return this.m}Z(b,a,c,d){a=Math.min(Math.max(a/100,-1),1);switch(b){case 9:this.o[0]=a,X(this,this.m.pan,a,c,d)}}};
self.Ge=class extends Y{constructor(b,a,c){super(b);this.T="tremolo";this.o=[a,c];this.m=W(this);this.m.gain.value=1-c/2;this.C=this.g.createOscillator();this.C.frequency.value=a;this.K=W(this);this.K.gain.value=c/2;this.C.connect(this.K);this.K.connect(this.m.gain);this.C.start(0)}l(){this.C.stop(0);this.C.disconnect();this.K.disconnect();this.m.disconnect();super.l()}U(b){this.m.disconnect();this.m.connect(b)}N(){return this.m}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[1]=
a;X(this,this.m.gain,1-a/2,c,d);X(this,this.K.gain,a/2,c,d);break;case 7:this.o[0]=a,X(this,this.C.frequency,a,c,d)}}};
self.Ee=class extends Y{constructor(b,a,c){super(b);this.T="ringmod";this.o=[a,c];this.A=W(this);this.j=W(this);this.j.gain.value=c;this.i=W(this);this.i.gain.value=1-c;this.Kb=W(this);this.Kb.gain.value=0;this.C=this.g.createOscillator();this.C.frequency.value=a;this.C.connect(this.Kb.gain);this.C.start(0);this.A.connect(this.Kb);this.A.connect(this.i);this.Kb.connect(this.j)}l(){this.C.stop(0);this.C.disconnect();this.Kb.disconnect();this.A.disconnect();this.j.disconnect();this.i.disconnect();super.l()}U(b){this.j.disconnect();
this.j.connect(b);this.i.disconnect();this.i.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[1]=a;X(this,this.j.gain,a,c,d);X(this,this.i.gain,1-a,c,d);break;case 7:this.o[0]=a,X(this,this.C.frequency,a,c,d)}}};
self.ze=class extends Y{constructor(b,a,c,d,e,f){super(b);this.T="distortion";this.o=[a,c,d,e,f];this.A=W(this);this.mc=W(this);this.lc=W(this);b=d;.01>b&&(b=.01);this.mc.gain.value=b;this.lc.gain.value=Math.pow(1/b,.6)*e;this.j=W(this);this.j.gain.value=f;this.i=W(this);this.i.gain.value=1-f;this.qc=this.g.createWaveShaper();this.Uc=new Float32Array(65536);for(e=0;32768>e;++e)f=e/32768,b=1.05*c*a-a,d=0>f?-f:f,d<a?b=d:(d=1-Math.exp(-(1/b)*(d-a)),b=a+b*d),f=b*(0>f?-1:1),this.Uc[32768+e]=f,this.Uc[32768-
e-1]=-f;this.qc.curve=this.Uc;this.A.connect(this.mc);this.A.connect(this.i);this.mc.connect(this.qc);this.qc.connect(this.lc);this.lc.connect(this.j)}l(){this.A.disconnect();this.mc.disconnect();this.qc.disconnect();this.lc.disconnect();this.j.disconnect();this.i.disconnect();super.l()}U(b){this.j.disconnect();this.j.connect(b);this.i.disconnect();this.i.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.o[4]=a,X(this,this.j.gain,a,c,d),X(this,this.i.gain,
1-a,c,d)}}};self.we=class extends Y{constructor(b,a,c,d,e,f){super(b);this.T="compressor";this.o=[a,c,d,e,f];this.m=this.g.createDynamicsCompressor();this.m.threshold.value=a;this.m.knee.value=c;this.m.ratio.value=d;this.m.attack.value=e;this.m.release.value=f}l(){this.m.disconnect();super.l()}U(b){this.m.disconnect();this.m.connect(b)}N(){return this.m}Z(){}};
self.ve=class extends Y{constructor(b,a,c){super(b);this.T="analyser";this.o=[a,c];this.m=this.g.createAnalyser();this.m.fftSize=a;this.m.smoothingTimeConstant=c;this.ae=new Float32Array(this.m.frequencyBinCount);this.oe=new Uint8Array(a);this.me=this.bb=0;b=this.v;b.Ta.add(this);S(b)}l(){this.v.Ta.delete(this);this.m.disconnect();super.l()}Ia(){this.m.getFloatFrequencyData(this.ae);this.m.getByteTimeDomainData(this.oe);const b=this.m.fftSize;let a=this.bb=0;for(var c=0;c<b;++c){let d=(this.oe[c]-
128)/128;0>d&&(d=-d);this.bb<d&&(this.bb=d);a+=d*d}c=self.jb.Re;this.bb=c(this.bb);this.me=c(Math.sqrt(a/b))}U(b){this.m.disconnect();this.m.connect(b)}N(){return this.m}Z(){}};"use strict";
async function Wb(b,a){b.ed=a.isInWorker;a=document.createElement("video");b.oc=!!a.requestVideoFrameCallback&&!b.h.Dc();const c=!!self.createImageBitmap;b.Ib=b.ed||c;return{postImageBitmaps:b.Ib,supportedFormats:{"webm-vp8":!!a.canPlayType("video/webm;codecs=vp8"),"webm-vp9":!!a.canPlayType("video/webm;codecs=vp9"),"webm-av1":!!a.canPlayType("video/webm;codecs=av01.0.00M.08"),"mp4-h264":!!a.canPlayType("video/mp4;codecs=avc1.420034"),"mp4-h265":!!a.canPlayType("video/mp4;codecs=hev1.1.2.L93.B0"),
"mp4-av1":!!a.canPlayType("video/mp4;codecs=av01.0.00M.08")}}}async function Xb(b,a){if(!b.Vc.has(a)){a.c3_rvfcId=a.requestVideoFrameCallback(()=>Xb(b,a));try{const c=a.c3_sequenceNumber++,d=await createImageBitmap(a);c>a.c3_lastFrameSequence&&(a.c3_imageBitmap=d,a.c3_lastFrameSequence=c)}catch(c){}}}function Z(b,a,c,d){b.Vc.has(a)||x(b,"playback-event",c,{type:d})}
self.ya.ib(class extends self.wc{constructor(b){super(b);this.Ib=this.oc=this.ed=this.Ma=!1;this.ec=this.zf=0;this.Vc=new WeakSet;p(this,"init",a=>Wb(this,a));y(this,"play",a=>{this.ca(a)});y(this,"pause",a=>{this.ha(a);a.pause()});y(this,"set-source",(a,c)=>{a.src=c.src;a.load()});y(this,"set-playback-time",(a,c)=>{try{a.currentTime=c.time}catch(d){console.error("[Video] Exception setting playback time: ",d)}});y(this,"set-playback-rate",(a,c)=>{try{a.playbackRate=c.rate}catch(d){console.error("[Video] Exception setting playback rate: ",
d)}});y(this,"set-looping",(a,c)=>{a.loop=c.isLooping});y(this,"set-muted",(a,c)=>{a.muted=c.isMuted});y(this,"set-volume",(a,c)=>{a.volume=c.volume});self.C3Video_GetElement=a=>z(this,a)}ca(b){this.h.ca(b);this.Ib&&this.oc&&-1===b.c3_rvfcId&&(b.c3_rvfcId=b.requestVideoFrameCallback(()=>Xb(this,b)))}ha(b){this.h.ha(b);this.Ib&&this.oc&&-1!==b.c3_rvfcId&&(b.cancelVideoFrameCallback(b.c3_rvfcId),b.c3_rvfcId=-1)}Bd(b,a){const c=document.createElement("video");c.crossOrigin="anonymous";c.playsInline=
!0;c.c3_imageBitmap=null;c.c3_rvfcId=-1;c.c3_sequenceNumber=0;c.c3_lastFrameSequence=-1;c.addEventListener("canplay",()=>Z(this,c,b,0));c.addEventListener("canplaythrough",()=>Z(this,c,b,1));c.addEventListener("ended",()=>Z(this,c,b,2));c.addEventListener("error",()=>Z(this,c,b,3));c.addEventListener("loadstart",()=>Z(this,c,b,4));c.addEventListener("playing",()=>Z(this,c,b,5));c.addEventListener("pause",()=>Z(this,c,b,6));c.addEventListener("stalled",()=>Z(this,c,b,7));const d=a.autoplay;0===d?(c.autoplay=
!1,c.preload="none"):1===d?(c.autoplay=!1,c.preload="auto"):c.autoplay=!0;a.src&&(c.src=a.src);2===d&&this.ca(c);this.ec++;w(this);return c}Id(){}Dd(b){this.ha(b);b&&!b.paused&&!b.ended&&0<b.currentTime&&b.pause();b.src="";this.ec=Math.max(this.ec-1,0);0===this.ec&&aa(this);this.Vc.add(b)}Ia(){const b={},a={sequenceNumber:this.zf++,videoData:b},c=[],d=[];for(const [e,f]of this.za.entries()){const g=f.Wa,h={currentTime:g.currentTime,playbackRate:g.playbackRate,duration:g.duration,videoWidth:g.videoWidth,
videoHeight:g.videoHeight};if(this.Ib)if(this.oc){const k=g.c3_imageBitmap;g.c3_imageBitmap=null;(h.imageBitmap=k)&&c.push(k)}else d.push(createImageBitmap(g).then(k=>{h.imageBitmap=k;c.push(k)}).catch(()=>{h.imageBitmap=null}));b[e.toString()]=h}Promise.all(d).then(()=>{this.ed?m(this,"state",a,!1,c):n(this,"state",a)})}});
